export const acronyms: Record<string, string[]> = {
  'ZT': ['Zero Trust  '],
  'XACML': [' eXtensible Access Control Markup Language  '],
  'WWLO': [' Win World\'s Largest Organizations'],
  'WWFO': [' Worldwide Field Operations'],
  'WTHDTAM': ['What the hell does that acronym mean'],
  'WS-Fed': ['Fed  Web-Services Federation  '],
  'WNA': [' Windows Native Authentication  '],
  'WLO': [' World\'s Largest Organizations'],
  'WI': [' Workforce Identity'],
  'WFW': ['Working From Work  '],
  'WFH': ['Working From Home  '],
  'WAM': ['Web Access Management  '],
  'WAF': ['Web Application Firewall  '],
  'VPC': ['Virtual Private Cloud  '],
  'VMT': ['Vision, Methods and Targets  '],
  'UX': ['User eXperience  '],
  'UPN': ['User Principal Name (Microsoft)  '],
  'UP': ['UI & Plugins'],
  'UI': ['User Interface  '],
  'UD': ['Universal Directory  '],
  'UAF': ['Universal Authentication Framework  '],
  'TTT': ['Train the Trainer  '],
  'TSE': ['Technical Support Engineer  '],
  'TPS': ['Technical Product Solutions'],
  'TPM': ['Technical Product Marketing Manager/Management (1/3 of the Product Triads)  '],
  'TOTP': ['Time-based One-Time Password algorithm  '],
  'TNO': ['Trust No One '],
  'TMM': ['Technical Marketing Manager/Management - Has now changed name to TPM   '],
  'TKO': ['Technical Kick-Off, formerly EKO'],
  'TFE': ['Technical Field Enablement  '],
  'TEEP': ['Test Engineering Escalation Point  '],
  'TCR': ['Technical Communication & Readiness  '],
  'SWA': ['Secure Web Authentication  '],
  'SUFM': ['Super User Feature Manager'],
  'SUBA': ['Security User Behaviour Analytics  '],
  'SU': ['Super User  '],
  'SSWS': ['Saasure Secure Web Service '],
  'SSPR': ['Self Service Password Reset  '],
  'SSP': ['Self-service publish for OIN devs'],
  'SSO': ['Single Sign On  '],
  'SSH': ['Secure SHell  '],
  'SRL': ['Secondary Release Test Lead'],
  'SREEP': ['Site Reliability Engineering Escalation Point  '],
  'SRE': ['Site Reliability Engineer  '],
  'SRB': ['Standards Review Board  '],
  'SQL': ['Structured Query Language  '],
  'SPNEGO': ['Simple and Protected GSSAPI Negotiation Mechanism (IETF RFC 2478)  '],
  'SPN': ['Service Packet Name  '],
  'SPA': ['Single Page Application  '],
  'SP': ['Service Provider  '],
  'SOW': ['Statement Of Work  '],
  'SOS': ['Scrum of Scrums'],
  'SOC': ['Security Operations Center  '],
  'SoC': ['Separation of Concerns (little "o")  ', 'Service Organization Control'],
  'SOAR': ['Security Orchestration, Automation and Response  '],
  'SME': ['Sales and Marketing Executive  ', 'Subject Matter Expert  '],
  'SLA': ['Service Level Agreement  '],
  'SKU': ['Stock Keeping Unit  '],
  'SIW': ['Sign-in Widget  '],
  'SIP': ['Security Intelligence Platform'],
  'SIEM': ['Security information and event management  '],
  'SDR': ['Sales Development Representative  '],
  'SCIM': ['System for Cross-domain Identity Management  '],
  'SAML': ['Security Assertion Markup Language  '],
  'SAM': ['Super Automatic Machine'],
  'S&R': ['  Security & Researcher  '],
  'RUM': ['Remote User Management'],
  'RRR': ['RRR (Rapid Recovery from Regressions)'],
  'RP': ['Relying Party  '],
  'REX': ['Research & EXploitation  '],
  'RDP': ['Remote Desktop Protocol  '],
  'RCA': ['Root-cause analysis'],
  'RADIUS': ['Remote Authentication Dial-In User Service  '],
  'RAAS': ['Registration as a Service  '],
  'QBR': ['Quarterly Business Review  '],
  'PWL': ['Password-less  '],
  'PS': ['Professional Services  '],
  'PRL': ['Primary Release Test Lead'],
  'PMM': ['Product Marketing Managers (1/3 of the Product Triads)  '],
  'PM': ['Product Manager/Management (1/3 of the Product Triads)  '],
  'PKCE': ['Proof Key for Code Exchange (pronounced "pixie")  '],
  'PIV': ['Personal Identity Verification  '],
  'PII': ['Personally Identifiable Information  '],
  'PHI': ['Personal Health Information  '],
  'PFV': ['Preview Fix Verification'],
  'PF': ['Preview Fix   '],
  'PEEP': ['Performance Engineering Escalation Point   '],
  'PDV': ['ost-deployment Verification'],
  'PD': ['PagerDuty  '],
  'PB': ['Preview Blocker'],
  'PAM': ['Pluggable Authentication Module   '],
  'OTP': ['One-time Password  '],
  'OSW': ['Okta Sign-in Widget  '],
  'OPP': ['n-Premise Provisioning  '],
  'OOTB': ['Out Of The Box  '],
  'OOO': ['Out of Office  '],
  'OOF': ['Out of Facility  '],
  'OOB': ['Out Of Band  '],
  'OMM': ['Okta Mobility Management  '],
  'OLM': ['Okta Lifecycle Management  '],
  'OKR': ['Objectives and Key Results  '],
  'OIN': ['Okta Integration Network, the new name from the OAN.'],
  'OIE': ['Okta Identity Engine'],
  'OIDC': ['Open ID Connect  '],
  'OIC': ['Okta Identity Cloud  '],
  'ODA': ['Okta Device Authenticator'],
  'OCC': ['Okta Cloud Connect '],
  'OAR': ['Okta Alignment Review'],
  'OAN': ['Okta Application Network, now called the Okta Integration Network.'],
  'OAG': ['Okta Access Gateway  '],
  'O4I': ['Okta For Infrastructure (New name for ScaleFT)  '],
  'O2K': ['Okta 2K (an Okta specific version of Global 2000 G2K))'],
  'NXT': ['eNduser eXperience Team'],
  'NSFW': ['Not Safe For Work  '],
  'NOC': ['Network Operations Center  '],
  'NMF': ['Not My Fault  '],
  'NLB': ['Network Load Balancer  '],
  'NFW': ['Not Feeling Well  '],
  'MVP': ['Minimum Viable Product  '],
  'MT': ['Migration Test'],
  'MSP': ['Managed Service Provider  '],
  'MSFT': ['Microsoft  '],
  'MS': ['Monthly Stretch'],
  'MIM': ['Mobile Identity Management  '],
  'MFA': ['Multi Factor Authentication  '],
  'MDF': ['Mutual Delivery Framework - an agreement between Okta and a customer on what will be delivered as part of a sales deal'],
  'MC': ['Monthly Commits'],
  'MBO': ['Management by Objective  '],
  'MAU': ['Monthly Active Users  '],
  'MAP': ['Mutual Action Plan  '],
  'M$': ['Microsoft  '],
  'LoE': ['Level of Effort  '],
  'LOE': ['Level of Effort  '],
  'LGTM': ['Looks Good To Me  '],
  'LET': ['Leaving Early Today  '],
  'LEA': ['Limited Early Access '],
  'LDAPi': ["LDAP Interface, Okta's LDAP as a Service offering "],
  'LDAP': ['Lightweight Directory Access Protocol  '],
  'LCM': ['Lifecycle Management  '],
  'LCA': ['Lifecycle Automation'],
  'KYC': ['Know Your Customer (from KuppingerCole "Leadership Compass for CIAM Platforms")  '],
  'KPI': ['Key Performance Indicator  '],
  'KCS': ['Knowledge Centered Service / Support '],
  'KBA': ['Knowledge Based Authentication  '],
  'JWT': ['JSON Web Token (pronounced: jot)  '],
  'JRP': ['Joint Requirements Planning'],
  'JIT': ['Just-in-time, with Okta this is usually referring to provisioning  '],
  'IWA': ['Integrated Windows Authentication  '],
  'ISV': ['Independent Software Vendor  '],
  'ISO': ['International Standards Organization  '],
  'IR': ['Investor Relations  '],
  'iPaaS': ['Integration Platform as a Service, like Azuqua.   '],
  'IHAC': ['I have a customer  '],
  'IGA': ['Identity, Governance & Administration  '],
  'IdX': ['Identity Experience  '],
  'IdP': ['Identity Provider  '],
  'IDaaS': ['Identity as a Service  '],
  'ICA': ['Import, Confirm, Activate, the steps for one of the Active Directory user import flows'],
  'IC': ['Individual Contributor  '],
  'IAA': ['Implicit App Assignments  '],
  'HIPAA': ['Health Insurance Portability and Accountability Act  '],
  'HFV': ['Hot Fix Verification'],
  'HARD': ['HoneyBadgers - Automating Router Deploys'],
  'GUI': ['Graphical User Interface  '],
  'GTM': ['Go To Market (Navigator)', 'Go To Market, Go To Meeting  '],
  'GSSAPI': ['Generic Security Service Application Program Interface'],
  'GSI': ['Global Systems Integrator  '],
  'GRC': ['Governance, Risk-Management, Compliance  '],
  'GH': ['GitHub  '],
  'GDPR': ['General Data Protection Regulation (European Union)  '],
  'GA': ['General Availability  '],
  'FTS': ['Following The Sun  '],
  'FLM': ['Feature Lifecycle Management'],
  'FISMA': ['Federal Information Security Management Act (United States, 2002)  '],
  'FIDO': ['Fast IDentity Online  '],
  'FF': ['Feature Flag  '],
  'FEDRAMP': ['Federal Risk and Authorization Management Program  '],
  'FAST': ['Eff’n Awesome Super Team or Future Access Success Team'],
  'FAM': ['Fartifactory Meow - a rewrite of Bacon'],
  'FAF': ['Fast as Fuck  '],
  'FAD': ['Future Architecture Document'],
  'ESPP': ['Employee Stock Purchase Program  '],
  'ERI': ['Endpoint Redirect Isolation'],
  'EOM': ["End of Message (used if the entire message is contained in the subject, and you don't need to read the body of the email)"],
  'EOD': ['End Of Day'],
  'EL': ['Expression Language'],
  'EKO': ['Engineering Kick-Off, now TKO'],
  'EHR': ['Electronic Health Record  '],
  'EEP': ['Engineering Escalation Point  '],
  'ECS': ['(Amazon) Elastic Container Service  '],
  'EBC': ['Executive Briefing Center  '],
  'EAP': ['Early Access Program OR Early Adopter Program   ', 'Extensible Authentication Protocol  '],
  'EAI': ['Enterprise Application Integration  '],
  'EA': ['Early Access  '],
  'DX': ['Developer Experience  '],
  'DT': ['Device Trust  '],
  'DSSO': ['Desktop Single Sign On '],
  'DoD': ['Director on Deck'],
  'DOD': ['Definition of Done  '],
  'DNR': ['Detection and Response - Security team'],
  'DL': ['Distribution List (email alias)'],
  'DDRR': ['Deep Dive Release Review'],
  'DBRI': ['Database Read Isolation  '],
  'DBRE': ['Database Reliability Engineer  '],
  'DBA': ['Database Administrator  '],
  'D4G': ['Docker for Good / Docker 4 Greg'],
  'CX': ['Customer Experience  '],
  'CVD': ['Cloud Virtual Directory (the old name for Universal Directory)  '],
  'CTA': ['Call to action  '],
  'CSR': ['Certificate Signing Request  '],
  'CSP': ['Customer Success Programs  '],
  'CSM': ['Customer Success Manager / Management  '],
  'CSG': ['Cloud Security Gateway  '],
  'CSAT': ['Customer Satisfaction  '],
  'CSA': ['Cloud Security Alliance  '],
  'CS': ['Customer Success  '],
  'CRUD': ['Create, Read, Update, Delete  '],
  'CRTR': ['Cell Router  '],
  'CRL': ['Certificate Revocation List  '],
  'CRAP':  ['Customer Regression Analysis Phase (deployment phase)'],
  'CPG': ['Consumer Packaged Goods  '],
  'CPC': ['Cloud Provisioning Connector, the new name for RUM '],
  'CLI': ['Command-line interface  '],
  'CLA': ['Contributor License Agreement  '],
  'CIL': ['Coming In Late. Typically used in WFH emails  '],
  'CIAM': ['Consumer Identity and Access Management  '],
  'CI': ['Customer Identity'],
  'CF': ['Code Freeze  '],
  'CDV': ['Configuration Deployment Verification'],
  'CCE': ['Customer Centric Engineering  '],
  'CB': ['CloudBoss'],
  'CASB': ['Cloud Access Security Broker (pronounced "Casby")  '],
  'CAPTCHA': ['Completely Automated Public Turing Test to Tell Computers and Human Apart  '],
  'CAM': ['Contextual Access Management  '],
  'CAC': ['Common Access Card  '],
  'CABO': ['Change Advisory Board for Operations'],
  'CAB': ['Customer Advisory Board  '],
  'CA': ['Certification Authority  '],
  'BVA': ['Business Value Assessment  '],
  'BOM': ['Bill Of Materials  '],
  'BHAG': ['Big Hairy Audacious Goal  '],
  'BDR': ['Business Development Representative  '],
  'BB': ['Big Brother concurrency limit (monolith capability)', 'Behavioral Biometrics  '],
  'B2E': ['Business to Employee (especially for internal, lifecycle use cases)'],
  'B2C': ['Business to Consumer or Business to Customer (often mentioned in CIAM use cases)  '],
  'B2B': ['Business to Business (usually partners)  '],
  'AuthZ': ['Authorization  '],
  'AuthN': ['Authentication – both an abbreviation and the API (/api/v1/authn)  '],
  'ATO': ['Authority to Operate (or, Account Take Over?)  '],
  'ASA': ['Advanced Server Access (Formerly ScaleFT)'],
  'API':  ['A\'M  API Access Management '],
  'AMR': ['Authentication Method Reference  '],
  'AMFA': ['Adaptive Multi-Factor Authentication  '],
  'AMAU': ['Annual Monthly Active Users  '],
  'ALB': ['Application Load Balancer  '],
  'AKF': ['Active Knowledge Framework - a repository of resources and learning materials that all Sales roles can leverage  '],
  'AIW': ['Application Integration Wizard'],
  'AFW': ['Android for Work  '],
  'AFK': ['Away from keyboard  '],
  'AELM': ['Admin Experience and License Management'],
  'ADFS': ['Active Directory Federation Services  '],
  'AD': ['Active Directory  '],
  'ACE': ['Assets, Collaboration and Enablement  '],
  'AC': ['App Catalog'],
  'AAD': ['Azure Active Directory  '],
  '2FA': ['Two Factor Authentication  '],
};
